---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: web-ui

outputs:
- name: build-output

params:
  TERM: dumb

run:
  path: web-ui/ci/tasks/build-web-ui/task.sh
