---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: web-service

outputs:
- name: build-output

params:
  TERM: dumb

run:
  path: web-service/ci/tasks/build-web-service/task.sh
