---
git-uri: https://github.com/bkamysz-pivotal/web-ui.git
git-branch: development
#web-ui-version-git-uri: git@github.com:bkamysz-pivotal/web.git
#web-ui-version-git-branch: version
s3-endpoint: s3.amazonaws.com
s3-access-key-id: SAMPLE786ASFD67AFT68
s3-secret-access-key: SAMPLE976a9gefa79w6egfa79w6efga97we6fgaw
s3-bucket-milestone: pivotal-bank-release-candidates
s3-bucket-release: pivotal-bank-release
cf-api-uri: api.cfapps.haas-46.pez.pivotal.io
cf-skip-ssl: true
cf-username: bkamysz
cf-password: paasword!
cf-org: bkamysz
cf-space: dev
cf-config-server-uri: https://github.com/bkamysz-pivotal/cf-SpringBootTrader-config
cf-config-server-label: master
cf-db-service: p-mysql
cf-db-service-plan: pre-existing-plan
cf-db-service-name: traderdb
#cf-db-service: cleardb spark traderdb
cf-web-ui-name: web-service
cf-web-ui-host: web-service
cf-web-service-services: discovery-service, circuit-breaker-dashboard, config-server
git-private-key: |
  -----BEGIN RSA PRIVATE KEY-----
  ...
  -----END RSA PRIVATE KEY-----
