---
resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: pivotalpa/cf-cli-resource
    tag: latest

groups:
- name: release
  jobs:
  - prepare-cf-env
  - build-web-service
- name: destroy
  jobs:
  - destroy

jobs:
- name: destroy
  public: true
  plan:
  - get: web-ui
  - put: cf-delete
    resource: cf-env
    params:
      command: delete
      app_name: web-service
      delete_mapped_routes: true
  - aggregate:
    - put: cf-delete-service
      resource: cf-env
      params:
        command: delete-service
        service_instance: {{cf-db-service-name}}
    - put: cf-delete-service
      resource: cf-env
      params:
        command: delete-service
        service_instance: config-server
    - put: cf-delete-service
      resource: cf-env
      params:
        command: delete-service
        service_instance: discovery-service
    - put: cf-delete-service
      resource: cf-env
      params:
        command: delete-service
        service_instance: circuit-breaker-dashboard

- name: build-web-service
  public: true
  serial: true
  plan:
  - get: web-ui
    passed: [ prepare-cf-env ]
    trigger: true
  - task: build
    file: web-ui/ci/tasks/build-web-service/task.yml
    params:
      ARTIFACT_ID: web-service
  - put: cf-zero-downtime-push
    resource: cf-env
    params:
      command: zero-downtime-push
      manifest: web-ui/manifest.yml
      environment_variables:
        TRUST_CERTS: {{cf-api-uri}}

- name: prepare-cf-env
  public: true
  serial: true
  plan:
  - get: web-ui
    trigger: true
  - aggregate:
    - put: cf-create-service
      resource: cf-env
      params:
        command: create-service
        service: {{cf-db-service}}
        plan: {{cf-db-service-plan}}
        service_instance: {{cf-db-service-name}}
        timeout: 300
        wait_for_service: true
    - put: cf-create-service
      resource: cf-env
      params:
        command: create-service
        service: p-config-server
        plan: standard
        service_instance: config-server
        timeout: 300
        wait_for_service: true
        configuration: '{ "count": 2, "git": { "uri": "https://github.com/bkamysz-pivotal/cf-SpringBootTrader-config", "cloneOnStart": "true" } }'
    - put: cf-create-service
      resource: cf-env
      params:
        command: create-service
        service: p-service-registry
        plan: standard
        service_instance: discovery-service
        timeout: 300
        wait_for_service: true
    - put: cf-create-service
      resource: cf-env
      params:
        command: create-service
        service: p-circuit-breaker-dashboard
        plan: standard
        service_instance: circuit-breaker-dashboard
        timeout: 300
        wait_for_service: true

resources:
- name: web-ui
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}
- name: cf-env
  type: cf-cli-resource
  source:
    api: {{cf-api-uri}}
    username: {{cf-username}}
    password: {{cf-password}}
    skip_cert_check: true
    org: {{cf-org}}
    space: {{cf-space}}
